#!/bin/bash
set -eo pipefail

INITIALIZED=$(cat /usr/local/bin/INITIALIZED)
if [[ $INITIALIZED -eq 0 ]]
then
    echo "Container is not yet initialized."
    echo "Setting HEALTHY=1."
    echo 1 | tee /usr/local/bin/HEALTHY 1>/dev/null
    exit 0
fi

if [[ $(netstat -lnpt | grep 8080 | wc -l) -eq 0 ]]
then
    echo "AdminServer is not listening on 8080."
    exit 1
fi
echo "AdminServer is listening on 8080."

host=$(hostname -i || echo 127.0.0.1)
echo "Host is @ $host."

request=$(curl -fLSs "http://$host:8080/commands/ruok")
echo "ZooKeeper response: $request, exit code: $?."
[[ $? -ne 0 ]] && exit 1

health=$(echo $request | jq -e ".error==null or error(.error)")
echo "ZooKeeper health check exit code: $?."
[[ $? -ne 0 ]] && exit 1

exit 0
